# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beltapp', '0003_auto_20170321_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default='3', max_length=10),
        ),
    ]
